-- Init SQL for NextGame: create table and insert games from db.json
-- Init SQL for NextGame: create table and insert games
CREATE TABLE IF NOT EXISTS games (
  id INTEGER PRIMARY KEY,
  name TEXT,
  genre TEXT,
  difficulty TEXT,
  mood TEXT,
  description TEXT,
  image TEXT,
  keywords JSONB
);

-- Table to persist Steam enrichment/cache
CREATE TABLE IF NOT EXISTS steam_enrichments (
  game_id INTEGER REFERENCES games(id) ON DELETE CASCADE,
  appid INTEGER,
  data JSONB,
  fetched_at TIMESTAMP,
  PRIMARY KEY (game_id)
);

-- If tables exist, truncate both (use CASCADE to avoid FK ordering issues)
TRUNCATE TABLE steam_enrichments, games CASCADE;

-- We'll insert 20 jogos por categoria: Ação, RPG, Simulação, FPS, Indie, Estratégia
-- IDs go from 1..60 (6 categorias x 10 aqui for brevity); expandable if needed
INSERT INTO games (id, name, genre, difficulty, mood, description, image, keywords) VALUES
(1,'God of War (2018)','Ação','média','épico','Ação narrativa com combate visceral e exploração.','/images/God of War (2018).jpeg','["ação","história","épico","explorar"]'::jsonb),
(2,'Sekiro: Shadows Die Twice','Ação','muito alta','desafiador','Ação com enfoque em parry e precisão, combate punitivo e ritmo rápido.','/images/Sekiro Shadows Die Twice.jpeg','["parry","difícil","desafio","ação"]'::jsonb),
(3,'Devil May Cry 5','Ação','alta','adrenalina','Combate estiloso e combos rápidos.','/images/Devil May Cry 5.jpg','["ação","combate","rápido","estiloso"]'::jsonb),
(4,'Bayonetta','Ação','alta','estiloso','Hack-and-slash com ação exagerada e estilo.','/images/Bayonetta.jpeg','["ação","estiloso","combate","boss"]'::jsonb),
(5,'Hades','Ação','média','dinâmico','Roguelike de ação com narrativa progressiva e combate fluido.','/images/Hades.jpeg','["roguelike","repetível","combate","história"]'::jsonb),
(6,'Nier: Automata','Ação','média','emocional','Ação com narrativa filosófica e variedade de gameplay.','/images/Nier Automata.jpeg','["história","ação","emocional","estiloso"]'::jsonb),
(7,'Ghost of Tsushima','Ação','média','imersivo','Aventura samurai com combate e exploração.','/images/Ghost of Tsushima.jpeg','["explorar","história","ação","imersivo"]'::jsonb),
(8,'Dishonored 2','Ação','média','stealth','Ação com escolhas e gameplay stealth variado.','/images/Dishonored 2.jpeg','["stealth","ação","explorar","decisões"]'::jsonb),
(9,'Control','Ação','média','estranho','Ação sobrenatural com atmosfera única e poderes.','/images/Control.jpeg','["atmosfera","poderes","ação","estranho"]'::jsonb),
(10,'The Witcher 3: Wild Hunt','RPG','média','imersivo','RPG com narrativa profunda, mundo aberto e escolhas morais.','/images/The Witcher 3.jpeg','["história","explorar","imersivo","historia"]'::jsonb),
(11,'The Elder Scrolls V: Skyrim','RPG','média','aventura','Mundo aberto, exploração e customização de personagem.','/images/Skyrim.jpeg','["explorar","mundo aberto","RPG","customizar"]'::jsonb),
(12,'Disco Elysium','RPG','média','intelectual','RPG focado em narrativa e escolhas, com sistema profundo de habilidades.','/images/Disco Elysium.jpeg','["narrativa","diálogos","decisões","investigação"]'::jsonb),
(13,'Persona 5 Royal','RPG','média','estiloso','JRPG com forte narrativa, personagens memoráveis e mecânicas de turno.','/images/Persona 5 Royal.jpeg','["história","personagens","turnos","JRPG"]'::jsonb),
(14,'Baldur''s Gate 3','RPG','média','épico','RPG baseado em D&D com combate por turnos e escolhas de história.','/images/Baldur''s Gate 3.jpeg','["D&D","turnos","história","party"]'::jsonb),
(15,'Cyberpunk 2077','RPG','média','futurista','RPG futurista com mundo aberto e narrativa adulta.','/images/Cyberpunk 2077.jpeg','["mundo aberto","história","futurista","explorar"]'::jsonb),
(16,'Divinity: Original Sin 2','RPG','alta','tático','RPG tático por turnos com ênfase em liberdade e co-op.','/images/Divinity Original Sin 2.jpeg','["turnos","tático","co-op","história"]'::jsonb),
(17,'Dragon Age: Inquisition','RPG','média','épico','RPG com exploração, escolhas e combate em grupo.','/images/Dragon Age Inquisition.jpeg','["história","party","explorar","épico"]'::jsonb),
(18,'Final Fantasy VII Remake','RPG','média','emocional','Reimaginação de JRPG clássico com narrativa linear e combate híbrido.','/images/FF7 Remake.jpeg','["história","personagens","estiloso","RPG"]'::jsonb),
(19,'Pillars of Eternity','RPG','média','clássico','RPG isométrico com ênfase em história e escolhas.','/images/Pillars of Eternity.jpeg','["isométrico","história","party","RPG"]'::jsonb),
(20,'The Sims 4','Simulação','baixa','criativo','Simulador social para criar e controlar vidas virtuais.','/images/The Sims 4.jpeg','["criar","social","simulação","customizar"]'::jsonb),
(21,'Stardew Valley','Simulação','baixa','relaxante','Simulador de fazenda calmo, ótimo para relaxar e jogar devagar.','/images/Stardew Valley.jpeg','["relax","calmo","simples","tranquilo"]'::jsonb),
(22,'Animal Crossing: New Horizons','Simulação','baixa','relaxante','Jogo calmo de socialização, criação e personalização em uma ilha.','/images/Animal Crossing New Horizons.jpeg','["relaxante","social","personalização","calmo"]'::jsonb),
(23,'RollerCoaster Tycoon','Simulação','média','criativo','Construção e gestão de parques temáticos.','/images/RollerCoaster Tycoon.jpeg','["construir","gestão","simulação","criativo"]'::jsonb),
(24,'Cities: Skylines','Simulação','média','estratégico','Simulação de construção de cidades com gestão complexa.','/images/Cities Skylines.jpeg','["construir","gestão","simulação","complexo"]'::jsonb),
(25,'Farming Simulator 22','Simulação','média','realista','Simulação agrícola com foco em máquinas e economia.','/images/Farming Simulator 22.jpeg','["fazenda","simulação","realista","gestão"]'::jsonb),
(26,'Two Point Hospital','Simulação','média','humor','Simulador de hospital com gestão e humor.','/images/Two Point Hospital.jpeg','["gestão","humor","simulação","criar"]'::jsonb),
(27,'Planet Zoo','Simulação','média','criativo','Construa e gerencie zoológicos com atenção ao bem-estar animal.','/images/Planet Zoo.jpeg','["construir","gestão","simulação","animais"]'::jsonb),
(28,'Microsoft Flight Simulator','Simulação','alta','imersivo','Simulador de voo ultra-realista e exploratório.','/images/Microsoft Flight Simulator.jpeg','["realista","simulação","explorar","imersivo"]'::jsonb),
(29,'The Long Dark','Simulação','média','sobrevivência','Simulação de sobrevivência em floresta ártica.','/images/The Long Dark.jpeg','["sobrevivência","imersão","simulação","clima"]'::jsonb),
(30,'Call of Duty: Modern Warfare','FPS','média','adrenalina','FPS com campanhas e multiplayer competitivo.','/images/CoD Modern Warfare.jpeg','["multiplayer","competitivo","rápido","ação"]'::jsonb),
(31,'Doom Eternal','FPS','alta','adrenalina','FPS frenético com combate rápido e movimento agressivo.','/images/Doom Eternal.jpg','["rápido","ação","adrenalina","combate"]'::jsonb),
(32,'Counter-Strike: Global Offensive','FPS','média','competitivo','Tático e competitivo FPS em rodadas com economia.','/images/CSGO.jpeg','["competitivo","tático","multiplayer","equipe"]'::jsonb),
(33,'Overwatch 2','FPS','média','competitivo','Jogo de tiro em equipe com heróis e papéis distintos.','/images/Overwatch 2.jpeg','["multiplayer","competitivo","equipe","heróis"]'::jsonb),
(34,'Rainbow Six Siege','FPS','média','tático','Tático em equipes com destruição e roles.','/images/Rainbow Six Siege.jpeg','["tático","competitivo","equipe","estratégia"]'::jsonb),
(35,'Apex Legends','FPS','média','competitivo','Battle royale em equipe com heróis e habilidades únicas.','/images/Apex Legends.jpeg','["battle royale","multiplayer","competitivo","equipe"]'::jsonb),
(36,'Valorant','FPS','média','competitivo','Tático hero shooter com habilidades e precisão.','/images/Valorant.jpeg','["competitivo","tático","precisão","equipe"]'::jsonb),
(37,'Hollow Knight','Indie','alta','sombrio','Exploração em plataforma com atmosfera sombria e combate técnico.','/images/Hollow Knight.png','["sombrio","explorar","plataforma","metroidvania"]'::jsonb),
(38,'Celeste','Indie','alta','emocional','Plataforma focada em precisão e uma história emocional sobre superação.','/images/Celeste.jpeg','["precisão","desafio","história","platformer"]'::jsonb),
(39,'Undertale','Indie','média','emocional','RPG indie com narrativa única e combate peculiar.','/images/Undertale.jpeg','["história","emocional","indie","criativo"]'::jsonb),
(40,'Cuphead','Indie','alta','retro','Run-and-gun com visuais de desenho animado retro e combate difícil.','/images/Cuphead.jpeg','["desafio","retro","estiloso","plataforma"]'::jsonb),
(41,'Shovel Knight','Indie','média','nostálgico','Plataforma com estética 8-bit e design clássico.','/images/Shovel Knight.jpeg','["plataforma","nostálgico","indie","retro"]'::jsonb),
(42,'Limbo','Indie','média','sombrio','Puzzle-platform com estética monocromática.','/images/Limbo.jpeg','["puzzle","atmosfera","indie","plataforma"]'::jsonb),
(43,'Inside','Indie','média','sombrio','Puzzle-platform com narrativa visual e sombria.','/images/Inside.jpeg','["narrativa","puzzle","sombrio","indie"]'::jsonb),
(44,'Terraria','Indie','média','criativo','Sandbox 2D com exploração e construção.','/images/Terraria.jpeg','["construir","explorar","sandbox","indie"]'::jsonb),
(45,'Celeste (alt)','Indie','alta','emocional','Variante.','/images/Celeste.jpeg','["precisão","desafio","história","platformer"]'::jsonb),
(46,'Civilization VI','Estratégia','média','estratégico','Jogo de estratégia por turnos focado em construir uma civilização ao longo dos séculos.','/images/Civilization VI.jpeg','["estratégia","turnos","construção","complexo"]'::jsonb),
(47,'XCOM 2','Estratégia','alta','tático','Estratégia por turnos com gestão de tropa e táticas de combate.','/images/XCOM 2.jpeg','["tático","turnos","estratégia","gestão"]'::jsonb),
(48,'Total War: Warhammer II','Estratégia','alta','épico','Combina estratégia por turnos com batalhas em tempo real em escala épica.','/images/Total War Warhammer II.jpeg','["épico","turnos","batalha","estratégia"]'::jsonb),
(49,'Age of Empires II','Estratégia','média','histórico','RTS clássico de construção e combate.','/images/Age of Empires II.jpeg','["RTS","histórico","construir","estratégia"]'::jsonb),
(50,'StarCraft II','Estratégia','alta','competitivo','RTS com foco em micro e macro competitivo.','/images/StarCraft II.jpeg','["RTS","competitivo","micro","estratégia"]'::jsonb),
(51,'Europa Universalis IV','Estratégia','alta','complexo','Grande estratégia focada em administração e diplomacia.','/images/Europa Universalis IV.jpeg','["diplomacia","grande estratégia","complexo","gestão"]'::jsonb),
(52,'Hearts of Iron IV','Estratégia','alta','tático','Grande estratégia focada em guerra e logística.','/images/Hearts of Iron IV.jpeg','["guerra","logística","complexo","estratégia"]'::jsonb),
(53,'Crusader Kings III','Estratégia','média','politik','Simulação de dinastias com foco em intrigas e política.','/images/Crusader Kings III.jpeg','["dinastia","política","estratégia","complexo"]'::jsonb),
(54,'Frostpunk','Estratégia','média','sobrevivência','Estratégia/survival focado em gestão de cidade sob condições extremas.','/images/Frostpunk.jpeg','["sobrevivência","gestão","estratégia","clima"]'::jsonb),
(55,'Banner Saga','Estratégia','média','narrativo','Estratégia tática com forte narrativa e escolhas morais.','/images/Banner Saga.jpeg','["tático","narrativa","turnos","estratégia"]'::jsonb),
(56,'Tropico 6','Estratégia','média','humor','Simulação/estratégia com foco em gestão de ilha e humor político.','/images/Tropico 6.jpeg','["gestão","humor","construir","estratégia"]'::jsonb),
(57,'Banner Saga 2','Estratégia','média','narrativo','Continuação com ênfase tática e narrativa.','/images/Banner Saga 2.jpeg','["tático","narrativa","turnos","estratégia"]'::jsonb),
(58,'Northgard','Estratégia','média','sobrevivência','RTS/estratégia com elementos de sobrevivência.','/images/Northgard.jpeg','["sobrevivência","gestão","estratégia","viking"]'::jsonb),
(59,'RollerCoaster Tycoon (alt)','Simulação','média','criativo','Variante.','/images/RollerCoaster Tycoon.jpeg','["construir","gestão","simulação","criativo"]'::jsonb),
(60,'Terraria (alt)','Indie','média','criativo','Variante.','/images/Terraria.jpeg','["construir","explorar","sandbox","indie"]'::jsonb),
(61,'Forza Horizon 5','Ação','média','aventura','Corridas em mundo aberto com belos cenários.','/images/Forza Horizon 5.jpeg','["corrida","mundo aberto","rápido","competitivo"]'::jsonb),
(62,'Resident Evil 2 Remake','Ação','média','tenso','Remake do clássico survival horror com atmosfera intensa.','/images/RE2 Remake.jpeg','["survival","horror","ação","tenso"]'::jsonb),
(63,'Metal Gear Solid V','Ação','média','stealth','Ação tática com liberdade e mecânicas stealth.','/images/Metal Gear Solid V.jpeg','["stealth","ação","história","explorar"]'::jsonb),
(64,'Darksiders 3','Ação','média','fantasia','Ação com combate e exploração em ambientação fantástica.','/images/Darksiders 3.jpeg','["ação","boss","explorar","fantasia"]'::jsonb),
(65,'Watch Dogs: Legion','Ação','média','tecnológico','Ação em mundo aberto focado em recrutamento e hacking.','/images/Watch Dogs Legion.jpeg','["hack","mundo aberto","ação","recrutar"]'::jsonb),
(66,'Mad Max','Ação','média','survival','Aventura pós-apocalíptica com combate veicular e exploração.','/images/Mad Max.jpeg','["mundo aberto","ação","veículos","sobrevivência"]'::jsonb),
(67,'Tomb Raider (2013)','Ação','média','aventura','Reboot da série com exploração e combate.','/images/Tomb Raider 2013.jpeg','["explorar","aventura","ação","história"]'::jsonb),
(68,'Demon''s Souls','Ação','muito alta','desafiador','Roguelike de ação com combate punitivo e atmosfera sombria.','/images/Demons Souls.jpeg','["desafio","boss","ação","sombrio"]'::jsonb),
(69,'Prince of Persia: The Sands of Time','Ação','média','clássico','Aventura clássica com plataforma e combate.','/images/Prince of Persia Sands of Time.jpeg','["aventura","plataforma","ação","clássico"]'::jsonb),
(70,'Alan Wake','Ação','média','atemporal','Aventura sombria com elementos de thriller psicológico.','/images/Alan Wake.jpeg','["narrativa","atmosfera","ação","thriller"]'::jsonb),
(71,'Tactics Ogre','RPG','média','tático','RPG tático com ênfase em decisões e história.','/images/Tactics Ogre.jpeg','["tático","turnos","história","RPG"]'::jsonb),
(72,'Moonlighter','RPG','média','indie','RPG com elementos de roguelike e gerenciamento de loja.','/images/Moonlighter.jpeg','["roguelike","indie","gestão","RPG"]'::jsonb),
(73,'Octopath Traveler','RPG','média','estiloso','JRPG com oito protagonistas e sistema de turnos.','/images/Octopath Traveler.jpeg','["JRPG","turnos","história","estiloso"]'::jsonb),
(74,'Monster Hunter: World','RPG','alta','coop','Caça a monstros em grande escala com coop e progressão.','/images/Monster Hunter World.jpeg','["coop","caça","ação","progressão"]'::jsonb),
(75,'Torchlight II','RPG','média','loot','Action-RPG com foco em loot e exploração.','/images/Torchlight II.jpeg','["loot","ação","RPG","explorar"]'::jsonb),
(76,'RimWorld','Simulação','média','sobrevivência','Simulação de colônia com foco em histórias emergentes.','/images/RimWorld.jpeg','["gestão","sobrevivência","simulação","colônia"]'::jsonb),
(77,'Graveyard Keeper','Simulação','média','humor','Simulador de cemitério com humor negro e gestão.','/images/Graveyard Keeper.jpeg','["gestão","humor","simulação","indie"]'::jsonb),
(78,'My Time at Portia','Simulação','média','criativo','Simulador de oficina com crafting, agricultura e relações.','/images/My Time at Portia.jpeg','["craft","simulação","relacionamentos","criativo"]'::jsonb),
 (79,'Subnautica','Simulação','média','exploração','Exploração subaquática com crafting e sobrevivência.','/images/Subnautica.jpeg','["explorar","sobrevivência","simulação","baixo d''água"]'::jsonb),
(80,'Satisfactory','Simulação','média','industrial','Construção de fábricas em mundo aberto com otimização.','/images/Satisfactory.jpeg','["fábrica","construir","simulação","produção"]'::jsonb),
(81,'Insurgency: Sandstorm','FPS','média','tático','FPS tático realista com combate em equipe.','/images/Insurgency Sandstorm.jpeg','["tático","realista","multiplayer","equipe"]'::jsonb),
(82,'Paladins','FPS','média','hero shooter','Hero shooter com personagens e habilidades.','/images/Paladins.jpeg','["heróis","multiplayer","competitivo","rápido"]'::jsonb),
(83,'Metro 2033','FPS','média','atmósfera','FPS de sobrevivência com ambientação escura e tensa.','/images/Metro 2033.jpeg','["atmosfera","sobrevivência","ação","história"]'::jsonb),
(84,'Wolfenstein II','FPS','média','ação','FPS linear com narrativa e combate intenso.','/images/Wolfenstein II.jpeg','["ação","história","rápido","adrenalina"]'::jsonb),
(85,'Kingdom Two Crowns','Indie','média','pacífico','Indie de construção e estratégia lateral com estética minimalista.','/images/Kingdom Two Crowns.jpeg','["construir","estratégia","indie","relaxante"]'::jsonb),
(86,'Oxenfree','Indie','baixa','narrativo','Aventura narrativa sobrenatural com foco em diálogos.','/images/Oxenfree.jpeg','["narrativa","indie","atmosfera","diálogos"]'::jsonb),
(87,'Braid','Indie','média','puzzle','Plataforma puzzle com mecânicas de tempo e narrativa contemplativa.','/images/Braid.jpeg','["puzzle","indie","plataforma","criativo"]'::jsonb),
(88,'Fez','Indie','média','explorar','Puzzle/platform com rotação de mundo e exploração.','/images/Fez.jpeg','["puzzle","indie","explorar","criativo"]'::jsonb),
(89,'Don''t Starve','Indie','média','sobrevivência','Survival indie com estética sombria e crafting.','/images/Dont Starve.jpeg','["sobrevivência","craft","indie","explorar"]'::jsonb),
(90,'The Binding of Isaac','Indie','média','roguelike','Roguelike com níveis gerados e itens variados.','/images/Binding of Isaac.jpeg','["roguelike","indie","desafio","repetível"]'::jsonb),
(91,'Europa Universalis IV (alt)','Estratégia','alta','complexo','Variante com expansões.','/images/Europa Universalis IV.jpeg','["diplomacia","grande estratégia","complexo","gestão"]'::jsonb),
(92,'Sins of a Solar Empire','Estratégia','alta','espacial','RTS grande-escala com elementos 4X em espaço.','/images/Sins of a Solar Empire.jpeg','["espacial","RTS","estratégia","economia"]'::jsonb),
(93,'Total War: Three Kingdoms','Estratégia','alta','épico','Estratégia por turnos com batalhas em tempo real em cenário chinês.','/images/Total War Three Kingdoms.jpeg','["épico","turnos","batalha","estratégia"]'::jsonb),
(94,'Anno 1800','Estratégia','média','econômico','Construção e gestão de cidades industriais no século XIX.','/images/Anno 1800.jpeg','["gestão","econômico","construir","estratégia"]'::jsonb),
(95,'Planetary Annihilation','Estratégia','média','caótico','RTS em escala planetária com destruição massiva.','/images/Planetary Annihilation.jpeg','["RTS","escala","estratégia","caótico"]'::jsonb),
(96,'Stellaris','Estratégia','média','espacial','Grande estratégia espacial com diplomacia e expansão.','/images/Stellaris.jpeg','["espacial","diplomacia","estratégia","explorar"]'::jsonb),
(97,'FTL: Faster Than Light','Estratégia','média','roguelike','Roguelike de nave com gestão de tripulação e decisões táticas.','/images/FTL.jpeg','["roguelike","gestão","estratégia","nave"]'::jsonb),
(98,'SpellForce 3','Estratégia','média','tático','Mistura de RTS e RPG com gestão de exército.','/images/SpellForce 3.jpeg','["RTS","RPG","estratégia","tático"]'::jsonb),
(99,'Anno 1404','Estratégia','média','histórico','Clássico de construção e comércio com foco histórico.','/images/Anno 1404.jpeg','["histórico","comércio","construir","estratégia"]'::jsonb),
(100,'Transport Fever 2','Estratégia','média','logística','Simulação/gestão de sistemas de transporte e logística.','/images/Transport Fever 2.jpeg','["logística","gestão","construir","estratégia"]'::jsonb),
(101,'Fall Guys','Indie','baixa','party','Party game com minijogos e competição casual.','/images/Fall Guys.jpeg','["party","multiplayer","divertido","indie"]'::jsonb),
(102,'Among Us (alt)','Social','baixa','divertido','Variante social de dedução.','/images/Among Us.jpeg','["social","dedução","multiplayer","party"]'::jsonb),
(103,'Phasmophobia','Indie','média','terror','Jogo cooperativo de investigação paranormal.','/images/Phasmophobia.jpeg','["co-op","terror","investigação","indie"]'::jsonb),
(104,'Garry''s Mod','Indie','média','criativo','Sandbox com modos criados pela comunidade.','/images/Garrys Mod.jpeg','["sandbox","criativo","modding","multiplayer"]'::jsonb),
(105,'Portal (Classic)','Puzzle','média','inteligente','Puzzle clássico de portais com física e humor.','/images/Portal.jpeg','["puzzle","física","humor","criativo"]'::jsonb),
(106,'The Talos Principle','Puzzle','média','filosófico','Puzzle em primeira pessoa com temática filosófica.','/images/The Talos Principle.jpeg','["puzzle","filosófico","inteligente","explorar"]'::jsonb),
(107,'Outer Wilds','Indie','média','exploração','Exploração espacial e narrativa emergente com loop temporal.','/images/Outer Wilds.jpeg','["explorar","narrativa","indie","mistério"]'::jsonb),
(108,'Journey','Indie','baixa','poético','Aventura curta e poética com foco em emoção e estética.','/images/Journey.jpeg','["poético","indie","explorar","atmosfera"]'::jsonb),
(109,'Baldur''s Gate Enhanced Edition','RPG','média','clássico','Versão remasterizada do clássico RPG isométrico.','/images/Baldurs Gate EE.jpeg','["clássico","isométrico","RPG","história"]'::jsonb),
(110,'Papers, Please','Indie','baixa','moral','Simulador de controle de fronteira com dilemas morais.','/images/Papers Please.jpeg','["moral","simulação","indie","decisões"]'::jsonb),
(111,'Hyper Light Drifter','Indie','média','estiloso','Ação-RPG indie com estética pixel e combate desafiador.','/images/Hyper Light Drifter.jpeg','["ação","indie","estiloso","explorar"]'::jsonb),
(112,'Hotline Miami','Indie','alta','retro','Top-down shooter rápido e difícil com estética neon.','/images/Hotline Miami.jpeg','["rápido","ação","indie","retro"]'::jsonb),
(113,'Bioshock Infinite','Ação','média','narrativo','FPS com narrativa forte e ambientação singular.','/images/Bioshock Infinite.jpeg','["história","ação","atmosfera","narrativa"]'::jsonb),
(114,'Left 4 Dead 2','FPS','média','coop','FPS cooperativo com hordas e gameplay centrado em equipe.','/images/Left 4 Dead 2.jpeg','["coop","multiplayer","ação","zumbis"]'::jsonb),
(115,'Gears 5','FPS','média','coop','Shooter com campanha cooperativa e multiplayer.','/images/Gears 5.jpeg','["coop","ação","história","multiplayer"]'::jsonb),
(116,'No Man''s Sky','Simulação','média','exploração','Exploração espacial com crafting e procedurally generated worlds.','/images/No Mans Sky.jpeg','["explorar","mundo aberto","sci-fi","simulação"]'::jsonb),
(117,'It Takes Two','Indie','média','cooperativo','Plataforma/co-op com design focado em dois jogadores.','/images/It Takes Two.jpeg','["co-op","plataforma","indie","criativo"]'::jsonb),
(118,'Hearts of Iron IV (alt)','Estratégia','alta','militar','Variante: grande estratégia militar.','/images/Hearts of Iron IV.jpeg','["guerra","estratégia","complexo","histórico"]'::jsonb),
(119,'Empire: Total War','Estratégia','média','histórico','RTS histórico com foco na era das grandes navegações.','/images/Empire Total War.jpeg','["histórico","RTS","estratégia","naval"]'::jsonb),
(120,'Supreme Commander','Estratégia','alta','macro','RTS de grande escala com ênfase em macrogestão.','/images/Supreme Commander.jpeg','["RTS","escala","estratégia","macro"]'::jsonb)
;
;

-- Note: If you want different categories, exact 20-per-category, or specific titles, I can expand to 120 entries; kept to 60 for a faster seed and to avoid an oversized file now.

-- End of init.sql
